version: 2

project_name: sentinelguard

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: sentinelguard
    main: ./cmd/checker/
    binary: sentinelguard
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Security
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: sosalejandro
    name: sentinelguard
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## SentinelGuard {{ .Version }}

    Security scanner for detecting backdoors and suspicious system configurations.
  footer: |
    ---

    **Full Changelog**: https://github.com/sosalejandro/sentinelguard/compare/{{ .PreviousTag }}...{{ .Tag }}
